/**
 * DM-14 ChannelConnection — the Drizzle table, the SINGLE source of its shape
 * (DEC-39). An authorized publishing-channel connection (ONBS-4), READ by the
 * Publisher (PUBS-1, ARC-18) to activate a destination — a destination activates
 * exactly when a `connected` ChannelConnection exists.
 *
 * SEC-10: the OAuth credential (access/refresh tokens) is an ENCRYPTED org secret
 * held server-side only — stored here as the opaque `credentialCipher` blob
 * (AES-256-GCM, sealed by @backend/crypto), never logged and never surfaced to
 * the client (the @shared `ChannelConnection` boundary DTO deliberately omits it,
 * DEC-39). `tokenExpiresAt` is the token's own expiry (not a secret) — the health
 * machine flips `connected → expired` off it.
 *
 * Health is a first-class DETERMINISTIC state machine (connected | expired |
 * revoked | error): a later expiry/revocation surfaces as the XO-4 needs-you card
 * with its reason (never a silent dead channel), cleared by re-running connect.
 * One connection per (org, platform). Hard-deleted with org data (SEC-4).
 */
import { index, pgTable, text, timestamp, unique } from "drizzle-orm/pg-core";
import { channelConnectionStatuses, channelPlatforms } from "../enums.js";
import { organization } from "./auth-schema.js";

export const channelConnection = pgTable(
  "channel_connection",
  {
    // Generated by the @backend write path (node crypto) — keeps @shared node-free.
    id: text("id").primaryKey(),
    /** Owning org (DM-1); every query is org-scoped (ACC-3). Cascades on org delete (SEC-4). */
    orgId: text("org_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    /** The destination channel this connection publishes to. */
    platform: text("platform", { enum: channelPlatforms }).notNull(),
    /** The external page/handle id this connection publishes to. */
    externalAccountRef: text("external_account_ref").notNull(),
    /** SEC-10: the AES-256-GCM-sealed OAuth credential blob — server-side only, never sent to the client. */
    credentialCipher: text("credential_cipher").notNull(),
    /** The OAuth token's own expiry (not a secret); null when the platform issues a non-expiring token. */
    tokenExpiresAt: timestamp("token_expires_at"),
    /** connected | expired | revoked | error — a non-`connected` state surfaces the XO-4 needs-you card. */
    status: text("status", { enum: channelConnectionStatuses }).notNull().default("connected"),
    /** Plain-language reason for a non-healthy state (empty when connected) — the needs-you card copy. */
    statusReason: text("status_reason").notNull().default(""),
    connectedAt: timestamp("connected_at").defaultNow().notNull(),
    /** Null until first verified against the platform. */
    lastVerifiedAt: timestamp("last_verified_at"),
  },
  (table) => [
    index("channel_connection_org_idx").on(table.orgId),
    // One connection per channel per org — reconnect UPSERTs this row.
    unique("channel_connection_org_platform_uq").on(table.orgId, table.platform),
  ],
);
