/**
 * DM-5 ChannelVariant — the Drizzle table, the SINGLE source of its shape (DEC-39).
 * The per-channel adaptation of a ContentItem master (master + ChannelVariant[],
 * GENS-2), each carrying its GENS-5 FIT verdict (fit | skipped + reason, retained
 * so the founder can preview/override) and its DELIVERY lifecycle state (distinct
 * from the ContentItem's EDITORIAL state — a multi-destination item cannot have one
 * status). Owned by Org (DM-1) via the parent ContentItem.
 */
import { boolean, index, pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { channelFitVerdicts, channelPlatforms, deliveryStates } from "../enums.js";
import { organization } from "./auth-schema.js";
import { contentItem } from "./content.js";

export const channelVariant = pgTable(
  "channel_variant",
  {
    // Generated by the @backend write path (node crypto) — keeps @shared node-free.
    id: text("id").primaryKey(),
    /** Owning org (DM-1), denormalized for org-scoped reads (ACC-3). */
    orgId: text("org_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    /** The master ContentItem this variant adapts (DM-5). */
    contentItemId: text("content_item_id")
      .notNull()
      .references(() => contentItem.id, { onDelete: "cascade" }),
    /** The destination channel. */
    platform: text("platform", { enum: channelPlatforms }).notNull(),
    /** The adapted body text for this channel (within its PUBS-2 technical profile). */
    body: text("body").notNull(),
    /** GENS-5 fit verdict — a skipped variant is RETAINED with its reason (VAL-3). */
    fitVerdict: text("fit_verdict", { enum: channelFitVerdicts }).notNull(),
    /** The visible, specific skip reason when not fit ("over policy 'no long stories on X'"). */
    fitReason: text("fit_reason").notNull().default(""),
    /** Whether a founder override forces this variant to ship despite a skip (GENS-5). */
    overridden: boolean("overridden").notNull().default(false),
    /** Per-destination DELIVERY state (only a fit-passed variant on an approved item enters `pending`). */
    deliveryState: text("delivery_state", { enum: deliveryStates }).notNull().default("pending"),
    /** The engagement-optimal delivery slot (PUB-1), null until scheduled. */
    scheduledFor: timestamp("scheduled_for"),
    /** The live link + timestamp once published (PUBS-3). */
    publishedUrl: text("published_url"),
    publishedAt: timestamp("published_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("channel_variant_org_idx").on(table.orgId),
    index("channel_variant_item_idx").on(table.contentItemId),
  ],
);
