/**
 * DM-5 ContentItem — the Drizzle table, the SINGLE source of its shape (DEC-39).
 * The output of the Content Engine (ARC-15 / GEN): the editorial MASTER story a
 * slot produced (GENS-7), owned by Org (DM-1). @backend imports this for
 * queries/migrations; @client/@news get the derived `ContentItem` TYPE via @shared.
 *
 * G1b SCOPE — the master + the EDITORIAL lifecycle state (DM-5 stateDiagram) +
 * the slot provenance (type/subject/designation) + the GENS-7 VAL verdict + the
 * OPSS-1 qaStatus gate. DEFERRED (documented, each its own migration): the
 * ChannelVariant[] table (G2 — per-channel adaptation + DELIVERY state), the
 * MediaAsset link + the awaiting_picture picture gate (G3, GENS-3/4), the
 * campaign tag (PRO-2), the long-form article body (NWS), the edit-diff log (APR-3).
 *
 * Editorial lifecycle (DM-5): draft → awaiting_picture → approved → skipped. G1b
 * lands a generated draft in `draft`; the awaiting_picture picture gate (GENS-3/4)
 * and the approve/skip transitions (APR) arrive with those verticals. A draft
 * whose VAL outcome escalated (GR-3/GR-8) stays `draft` with `escalated: true` —
 * at TL0 every draft needs founder approval anyway; the flag records WHY it can
 * never auto-advance (the GENS-7 backstop) so APR can surface the reason.
 */
import { boolean, index, pgTable, text, timestamp } from "drizzle-orm/pg-core";
import {
  contentTypes,
  editorialStates,
  qaStatuses,
  slotDesignations,
  valOutcomes,
} from "../enums.js";
import { organization } from "./auth-schema.js";

export const contentItem = pgTable(
  "content_item",
  {
    // Generated by the @backend write path (node crypto) — keeps @shared node-free,
    // mirroring memory_entry (the table has no $defaultFn).
    id: text("id").primaryKey(),
    /** Owning org (DM-1). Every query is org-scoped (ACC-3). */
    orgId: text("org_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    /** Editorial lifecycle state (DM-5); a generated draft lands in `draft`. */
    editorialState: text("editorial_state", { enum: editorialStates }).notNull().default("draft"),
    // ── slot provenance (GEN-1 pairing): the taxonomy TYPE + agenda SUBJECT + overlay.
    /** The content TYPE from the taxonomy — HOW the slot frames its subject (GEN-1). */
    contentType: text("content_type", { enum: contentTypes }).notNull(),
    /** The agenda SUBJECT — WHAT the post is about (a TOPS-4 topic, GEN-1). */
    subject: text("subject").notNull(),
    /** The plan-time overlay designation the master honors (GEN-1 v4). */
    designation: text("designation", { enum: slotDesignations }).notNull().default("none"),
    // ── the master story (GENS-7).
    title: text("title").notNull(),
    body: text("body").notNull(),
    /** The founder-facing "why this, why now" line (GEN-1 ReasonLine). */
    reasonLine: text("reason_line").notNull(),
    // ── the GENS-7 VAL verdict at generation.
    /** The VAL chain outcome (PIPE-2): pass | regenerate | escalate. */
    valOutcome: text("val_outcome", { enum: valOutcomes }).notNull(),
    /** True when VAL escalated (GR-3/GR-8) — this draft can never auto-advance. */
    escalated: boolean("escalated").notNull().default(false),
    /** Human-readable summary of the guardrail findings (empty when clean) — APR shows it. */
    valSummary: text("val_summary").notNull().default(""),
    /** External-sourced content (GR-5 citation applies). */
    isExternal: boolean("is_external").notNull().default(false),
    /** Cohort-1 operator-QA gate (OPSS-1); `n/a` (default) once the per-org dial is off. */
    qaStatus: text("qa_status", { enum: qaStatuses }).notNull().default("n/a"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    // Org-scoped lookups (ACC-3); the Ready surface (APRS-1) lists by org + state.
    index("content_item_org_idx").on(table.orgId),
    index("content_item_org_state_idx").on(table.orgId, table.editorialState),
  ],
);
