/**
 * EditDiff — the DM-5 edit-diff log (APRS-3), the Drizzle table + the SINGLE
 * source of its shape (DEC-39). Part of the DM-5 ContentItem aggregate (its
 * "edit-diff log", deferred in content.ts until APR) — NOT a new top-level entity.
 *
 * Every founder EDIT (inline Edit on the master or a variant, or an accepted
 * redirect) appends one row: the before/after text + what was targeted. The
 * APRS-3 learning loop READS these rows to detect RECURRING edit patterns and
 * PROPOSE Memory styleRules/taboos (the detection is an LLM/statistical judgment —
 * a documented follow-on; this table is the data it reads). Append-only. Owned by
 * Org (DM-1), hard-deleted with org data (SEC-4).
 */
import { index, pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { organization } from "./auth-schema.js";
import { contentItem } from "./content.js";

export const editDiff = pgTable(
  "edit_diff",
  {
    // Generated by the @backend write path (node crypto) — keeps @shared node-free.
    id: text("id").primaryKey(),
    /** Owning org (DM-1); every query is org-scoped (ACC-3). Cascades on org delete (SEC-4). */
    orgId: text("org_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    /** The edited ContentItem (DM-5). Cascades with the item. */
    contentItemId: text("content_item_id")
      .notNull()
      .references(() => contentItem.id, { onDelete: "cascade" }),
    /** The per-channel variant edited, or null for a master edit. A soft ref (the item cascade cleans up). */
    variantId: text("variant_id"),
    /** The text before the edit. */
    beforeText: text("before_text").notNull(),
    /** The text after the edit — the diff APRS-3's pattern detection reads. */
    afterText: text("after_text").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("edit_diff_org_idx").on(table.orgId)],
);
