/**
 * DM-2 MemoryEntry — the Drizzle table, the SINGLE source of its shape (DEC-39).
 * The store behind @backend/memory (ARC-11): the org's permanent knowledge as
 * typed, attributed, embedded entries (MEM-1). Owned by Org (DM-1 =
 * BetterAuth `organization`). @backend imports this for queries/migrations;
 * @client/@news get the derived `MemoryEntry` TYPE via @shared (entities/).
 *
 * Design notes (MEMS-1/2/4/6):
 * - `subjectKey` is the DETERMINISTIC dedup + asked-set key (MEMS-2/MEMS-6):
 *   structured entries → `kind + normalized subject`; free-form fact/story →
 *   the normalized full assertion. Merge happens ONLY on an identical active
 *   key; different keys stay separate (bias-to-not-merge). Computed in the
 *   write path, never by embedding proximity.
 * - Supersession is SOFT (MEMS-2): a correction sets `supersededAt`/
 *   `supersededBy` on the prior row (retained with provenance, VAL-3) and
 *   inserts the new active row. A row is ACTIVE iff `supersededAt IS NULL`.
 *   Hard delete is reserved for the wrong-org escape + BIL-2 purge (SEC-4).
 * - `embedding` is nullable: the write persists first, then embeds (the
 *   ADR-0008 LLM port); the keyless dev fallback fills it deterministically.
 *   Retrieval (MEMS-4) is cosine distance over this column (pgvector, ADR-0002).
 */
import { relations } from "drizzle-orm";
import { boolean, index, jsonb, pgTable, text, timestamp, vector } from "drizzle-orm/pg-core";
import type { MemorySource } from "../entities/memory-source.js";
import { memoryEntryKinds } from "../enums.js";
import { organization } from "./auth-schema.js";

/** The embedding dimension — Gemini `gemini-embedding-001` at 1536 (ADR-0008, DEC-40). */
export const MEMORY_EMBEDDING_DIM = 1536 as const;

export const memoryEntry = pgTable(
  "memory_entry",
  {
    // Generated by the @backend write path (which has node crypto), mirroring
    // the BetterAuth tables' no-default text ids — keeps @shared node-free.
    id: text("id").primaryKey(),
    /** Owning org (DM-1). Every query is org-scoped (ACC-3). */
    orgId: text("org_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    /** One of the seven DM-2 types (MEMS-1). */
    // Single-sourced from the enums.ts const tuple — narrows the column to the
    // seven-type union (drizzle accepts a readonly literal tuple).
    kind: text("kind", { enum: memoryEntryKinds }).notNull(),
    /**
     * The subject/title — the person/program/event name, or a short subject for
     * a fact/story. Nullable for a subject-less free-form fact.
     */
    subject: text("subject"),
    /** The assertion/body of the entry. */
    content: text("content").notNull(),
    /** Deterministic dedup + asked-set key (MEMS-2/MEMS-6). */
    subjectKey: text("subject_key").notNull(),
    /** Provenance (MEMS-1) — natively typed jsonb (constitution: DB JSON mapped to TS). */
    source: jsonb("source").$type<MemorySource>().notNull(),
    /**
     * An inference / sensible default not yet founder-confirmed (MEMS-5, ONBS-2):
     * surfaced as a correctable AssumedNote. A silent guess is forbidden (VAL-3).
     */
    assumed: boolean("assumed").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    /** MEMS-1 bare-approval reinforcement touch (a recency bump), else null. */
    reinforcedAt: timestamp("reinforced_at"),
    /** Set when this row is superseded by a correction (MEMS-2); null ⇒ active. */
    supersededAt: timestamp("superseded_at"),
    /** The active row that superseded this one (MEMS-2 self-reference). */
    supersededBy: text("superseded_by"),
    /** The retrieval embedding (ADR-0008 dim 1536); null until embedded. */
    embedding: vector("embedding", { dimensions: MEMORY_EMBEDDING_DIM }),
  },
  (table) => [
    // Org-scoped lookups (ACC-3) + the dedup/merge lookup by deterministic key
    // among active rows (MEMS-2), and the deterministic active rule/taboo
    // overlay query by kind (MEMS-3/MEMS-4, never similarity-gated).
    index("memory_entry_org_idx").on(table.orgId),
    index("memory_entry_org_key_idx").on(table.orgId, table.subjectKey),
    index("memory_entry_org_kind_idx").on(table.orgId, table.kind),
    // Approximate-nearest-neighbour index for cosine retrieval (pgvector HNSW).
    index("memory_entry_embedding_idx").using("hnsw", table.embedding.op("vector_cosine_ops")),
  ],
);

/** MemoryEntry ⇒ Org (DM-1) and the supersession self-link (MEMS-2). */
export const memoryEntryRelations = relations(memoryEntry, ({ one }) => ({
  org: one(organization, {
    fields: [memoryEntry.orgId],
    references: [organization.id],
  }),
  supersededByEntry: one(memoryEntry, {
    fields: [memoryEntry.supersededBy],
    references: [memoryEntry.id],
    relationName: "supersession",
  }),
}));
